---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: 'github-actions'
      # Workflow files stored in the
      # default location of `.github/workflows`
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
