---
version: 2

registries:
 terraform:
   type: terraform-registry
   url: https://terraform-mirror.yandexcloud.net/

updates:
 - package-ecosystem: "terraform"
   directory: "/"
   registries:
     - spacelift
   schedule:
     interval: "daily"